<template>
	<view style="padding: 40rpx;">
		<div><p><span style="padding: 0px 16px 0px 0px; margin: 0px; display: inline-block; height: 45px; line-height: 45px; font-size: 28px;">公司业务</span></p><p class="cont-cbisniess" style="margin-top: 0px; margin-bottom: 0px; padding: 0px; font-size: 14px;"><br></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2;"><span style="font-family: 微软雅黑; font-size: 18px;"><span style="font-weight: 700;">股权投资（国内&amp;国外）</span></span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<span style="font-family: 微软雅黑;">投资于未上市公司股权，通过对初创型企业、成熟型企业和行业龙头企业的不同投资策略，以企业次轮融资、境内外上市或被并购等多种方式实现投资的退出。</span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;"><span style="font-family: 微软雅黑;">&nbsp; &nbsp; &nbsp; &nbsp;投资于美国、欧洲、以色列、日本等国家与地区的创新型生物技术企业；投资于海外创新技术的中国研发与商业化；链接中国医药企业与海外医疗产业资源；致力于为中国的医药创新注入全球视野。</span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;"><span style="font-family: 微软雅黑;"><br></span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2;"><span style="font-family: 微软雅黑; font-size: 18px;"><span style="font-weight: 700;">夹层投资</span></span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;">&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<span style="font-family: 微软雅黑;">为优质企业和优质募投项目提供融资服务，力求解决企业多样化的融资需求。</span>&nbsp; &nbsp;&nbsp;&nbsp;</p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;"><br></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2;"><span style="padding: 0px; margin: 0px;"><span style="font-family: 微软雅黑; font-size: 18px;"><span style="font-weight: 700;">并购投资</span></span></span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;"><br></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;">&nbsp; &nbsp; &nbsp;&nbsp;<span style="font-family: 微软雅黑;">为上市公司并购交易提供资金；与上市公司或控股股东合作成立并购基金收购标的，并对上市公司进行市值提升管理；帮助上市公司反收购及维护控股权稳定；着重成立产业并购基金，与上市公司及其控股股东、私募基金管理机构在资金、项目、管理和退出渠道上，实现差异互补、强强联合。</span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; line-height: 2.5;"><img src="http://gf.wcloudvip.xyz/Public/uploads/article/20210608/1623136579506506.jpg" alt="7162968648522565"><br></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px;"><span style="font-size: 12px;">&nbsp;</span></p><p style="margin-top: 0px; margin-bottom: 0px; padding: 0px;"><br></p><p><br></p><p><span style="padding: 0px; margin: 0px 1em; line-height: 2.5em;"></span></p><p><br></p><p><br></p></div>
	</view>
</template>

<script>
</script>

<style>
</style>
